export const HOBBIES = [
  // 📖 Creative & Artistic
  { id: "reading", title: "Reading", icon: "📚", category: "Creative & Artistic" },
  { id: "writing", title: "Writing", icon: "✍️", category: "Creative & Artistic" },
  { id: "blogging", title: "Blogging", icon: "📝", category: "Creative & Artistic" },
  { id: "poetry", title: "Poetry", icon: "📝", category: "Creative & Artistic" },
  { id: "painting", title: "Painting", icon: "🎨", category: "Creative & Artistic" },
  { id: "drawing", title: "Drawing", icon: "✏️", category: "Creative & Artistic" },
  { id: "calligraphy", title: "Calligraphy", icon: "🖋️", category: "Creative & Artistic" },
  { id: "photography", title: "Photography", icon: "📷", category: "Creative & Artistic" },
  { id: "film-making", title: "Film Making", icon: "🎬", category: "Creative & Artistic" },
  { id: "music", title: "Music", icon: "🎵", category: "Creative & Artistic" },
  { id: "guitar", title: "Guitar", icon: "🎸", category: "Creative & Artistic" },
  { id: "piano", title: "Piano", icon: "🎹", category: "Creative & Artistic" },
  { id: "singing", title: "Singing", icon: "🎤", category: "Creative & Artistic" },
  { id: "dancing", title: "Dancing", icon: "💃", category: "Creative & Artistic" },
  { id: "crafting", title: "Crafting", icon: "🧶", category: "Creative & Artistic" },
  { id: "woodworking", title: "Woodworking", icon: "🪚", category: "Creative & Artistic" },
  { id: "lego-building", title: "LEGO Building", icon: "🧱", category: "Creative & Artistic" },
  { id: "cooking", title: "Cooking", icon: "🍳", category: "Creative & Artistic" },
  { id: "baking", title: "Baking", icon: "🧁", category: "Creative & Artistic" },
  { id: "mixology", title: "Mixology", icon: "🍹", category: "Creative & Artistic" },
  { id: "coding", title: "Coding", icon: "💻", category: "Creative & Artistic" },
  { id: "animation", title: "Animation", icon: "🎞️", category: "Creative & Artistic" },
  { id: "graphic-design", title: "Graphic Design", icon: "🖌️", category: "Creative & Artistic" },

  // 🏃 Active & Outdoor
  { id: "hiking", title: "Hiking", icon: "🥾", category: "Active & Outdoor" },
  { id: "running", title: "Running", icon: "🏃", category: "Active & Outdoor" },
  { id: "cycling", title: "Cycling", icon: "🚴", category: "Active & Outdoor" },
  { id: "mountain-biking", title: "Mountain Biking", icon: "🚵", category: "Active & Outdoor" },
  { id: "skateboarding", title: "Skateboarding", icon: "🛹", category: "Active & Outdoor" },
  { id: "rollerblading", title: "Rollerblading", icon: "🛼", category: "Active & Outdoor" },
  { id: "skiing", title: "Skiing", icon: "⛷️", category: "Active & Outdoor" },
  { id: "snowboarding", title: "Snowboarding", icon: "🏂", category: "Active & Outdoor" },
  { id: "surfing", title: "Surfing", icon: "🏄", category: "Active & Outdoor" },
  { id: "swimming", title: "Swimming", icon: "🏊", category: "Active & Outdoor" },
  { id: "diving", title: "Diving", icon: "🤿", category: "Active & Outdoor" },
  { id: "kayaking", title: "Kayaking", icon: "🛶", category: "Active & Outdoor" },
  { id: "canoeing", title: "Canoeing", icon: "🚣", category: "Active & Outdoor" },
  { id: "sailing", title: "Sailing", icon: "⛵", category: "Active & Outdoor" },
  { id: "rock-climbing", title: "Rock Climbing", icon: "🧗", category: "Active & Outdoor" },
  { id: "martial-arts", title: "Martial Arts", icon: "🥋", category: "Active & Outdoor" },
  { id: "boxing", title: "Boxing", icon: "🥊", category: "Active & Outdoor" },
  { id: "archery", title: "Archery", icon: "🏹", category: "Active & Outdoor" },
  { id: "horseback-riding", title: "Horseback Riding", icon: "🐎", category: "Active & Outdoor" },
  { id: "fishing", title: "Fishing", icon: "🎣", category: "Active & Outdoor" },
  { id: "camping", title: "Camping", icon: "🏕️", category: "Active & Outdoor" },
  { id: "gardening", title: "Gardening", icon: "🪴", category: "Active & Outdoor" },
  { id: "yoga", title: "Yoga", icon: "🧘", category: "Active & Outdoor" },
  { id: "working-out", title: "Working Out", icon: "🏋️", category: "Active & Outdoor" },
  { id: "pilates", title: "Pilates", icon: "🤸", category: "Active & Outdoor" },

  // 🎲 Social & Entertainment
  { id: "gaming", title: "Gaming", icon: "🎮", category: "Social & Entertainment" },
  { id: "board-games", title: "Board Games", icon: "🎲", category: "Social & Entertainment" },
  { id: "card-games", title: "Card Games", icon: "🃏", category: "Social & Entertainment" },
  { id: "movies", title: "Movies", icon: "🍿", category: "Social & Entertainment" },
  { id: "theater", title: "Theater", icon: "🎭", category: "Social & Entertainment" },
  { id: "concerts", title: "Concerts", icon: "🎶", category: "Social & Entertainment" },
  { id: "karaoke", title: "Karaoke", icon: "🎤", category: "Social & Entertainment" },
  { id: "trivia", title: "Trivia", icon: "❓", category: "Social & Entertainment" },
  { id: "traveling", title: "Traveling", icon: "✈️", category: "Social & Entertainment" },
  { id: "volunteering", title: "Volunteering", icon: "🤝", category: "Social & Entertainment" },

  // 🛋️ Chill & Solo
  { id: "learning", title: "Learning", icon: "🧠", category: "Chill & Solo" },
  { id: "meditation", title: "Meditation", icon: "🕉️", category: "Chill & Solo" },
  { id: "journaling", title: "Journaling", icon: "📓", category: "Chill & Solo" },
  { id: "puzzles", title: "Puzzles", icon: "🧩", category: "Chill & Solo" },
  { id: "chess", title: "Chess", icon: "♟️", category: "Chill & Solo" },
  { id: "thrifting", title: "Thrifting", icon: "🪙", category: "Chill & Solo" },
  { id: "bird-watching", title: "Bird Watching", icon: "🐦", category: "Chill & Solo" },
  { id: "astrology", title: "Astrology", icon: "🔮", category: "Chill & Solo" },
  { id: "stargazing", title: "Stargazing", icon: "✨", category: "Chill & Solo" },
  { id: "podcasts", title: "Podcasts", icon: "🎧", category: "Chill & Solo" },
  { id: "language-learning", title: "Language Learning", icon: "🌍", category: "Chill & Solo" },
  { id: "knitting", title: "Knitting", icon: "🧵", category: "Chill & Solo" },
  { id: "sewing", title: "Sewing", icon: "🪡", category: "Chill & Solo" },
];
