export const HOBBIES = [
  // 📖 Creative & Artistic
  { id: "reading", title: "Reading", icon: "📚" },
  { id: "writing", title: "Writing", icon: "✍️" },
  { id: "poetry", title: "Poetry", icon: "📝" },
  { id: "painting", title: "Painting", icon: "🎨" },
  { id: "drawing", title: "Drawing", icon: "✏️" },
  { id: "calligraphy", title: "Calligraphy", icon: "🖋️" },
  { id: "photography", title: "Photography", icon: "📷" },
  { id: "film-making", title: "Film Making", icon: "🎬" },
  { id: "music", title: "Music", icon: "🎵" },
  { id: "guitar", title: "Guitar", icon: "🎸" },
  { id: "piano", title: "Piano", icon: "🎹" },
  { id: "singing", title: "Singing", icon: "🎤" },
  { id: "dancing", title: "Dancing", icon: "💃" },
  { id: "crafting", title: "Crafting", icon: "🧶" },
  { id: "woodworking", title: "Woodworking", icon: "🪚" },
  { id: "lego-building", title: "LEGO Building", icon: "🧱" },
  { id: "cooking", title: "Cooking", icon: "🍳" },
  { id: "baking", title: "Baking", icon: "🧁" },
  { id: "mixology", title: "Mixology", icon: "🍹" },
  { id: "coding", title: "Coding", icon: "💻" },
  { id: "animation", title: "Animation", icon: "🎞️" },
  { id: "graphic-design", title: "Graphic Design", icon: "🖌️" },

  // 🏃 Active & Outdoor
  { id: "hiking", title: "Hiking", icon: "🥾" },
  { id: "running", title: "Running", icon: "🏃" },
  { id: "cycling", title: "Cycling", icon: "🚴" },
  { id: "mountain-biking", title: "Mountain Biking", icon: "🚵" },
  { id: "skateboarding", title: "Skateboarding", icon: "🛹" },
  { id: "rollerblading", title: "Rollerblading", icon: "🛼" },
  { id: "skiing", title: "Skiing", icon: "⛷️" },
  { id: "snowboarding", title: "Snowboarding", icon: "🏂" },
  { id: "surfing", title: "Surfing", icon: "🏄" },
  { id: "swimming", title: "Swimming", icon: "🏊" },
  { id: "diving", title: "Diving", icon: "🤿" },
  { id: "kayaking", title: "Kayaking", icon: "🛶" },
  { id: "canoeing", title: "Canoeing", icon: "🚣" },
  { id: "sailing", title: "Sailing", icon: "⛵" },
  { id: "rock-climbing", title: "Rock Climbing", icon: "🧗" },
  { id: "martial-arts", title: "Martial Arts", icon: "🥋" },
  { id: "boxing", title: "Boxing", icon: "🥊" },
  { id: "archery", title: "Archery", icon: "🏹" },
  { id: "horseback-riding", title: "Horseback Riding", icon: "🐎" },
  { id: "fishing", title: "Fishing", icon: "🎣" },
  { id: "camping", title: "Camping", icon: "🏕️" },
  { id: "gardening", title: "Gardening", icon: "🪴" },
  { id: "yoga", title: "Yoga", icon: "🧘" },
  { id: "working-out", title: "Working Out", icon: "🏋️" },
  { id: "pilates", title: "Pilates", icon: "🤸" },

  // 🎲 Social & Entertainment
  { id: "gaming", title: "Gaming", icon: "🎮" },
  { id: "board-games", title: "Board Games", icon: "🎲" },
  { id: "card-games", title: "Card Games", icon: "🃏" },
  { id: "movies", title: "Movies", icon: "🍿" },
  { id: "theater", title: "Theater", icon: "🎭" },
  { id: "concerts", title: "Concerts", icon: "🎶" },
  { id: "karaoke", title: "Karaoke", icon: "🎤" },
  { id: "trivia", title: "Trivia", icon: "❓" },
  { id: "traveling", title: "Traveling", icon: "✈️" },
  { id: "volunteering", title: "Volunteering", icon: "🤝" },

  // 🛋️ Chill & Solo
  { id: "learning", title: "Learning", icon: "🧠" },
  { id: "meditation", title: "Meditation", icon: "🕉️" },
  { id: "journaling", title: "Journaling", icon: "📓" },
  { id: "puzzles", title: "Puzzles", icon: "🧩" },
  { id: "chess", title: "Chess", icon: "♟️" },
  { id: "thrifting", title: "Thrifting", icon: "🪙" },
  { id: "bird-watching", title: "Bird Watching", icon: "🐦" },
  { id: "astrology", title: "Astrology", icon: "🔮" },
  { id: "stargazing", title: "Stargazing", icon: "✨" },
  { id: "podcasts", title: "Podcasts", icon: "🎧" },
  { id: "language-learning", title: "Language Learning", icon: "🌍" },
  { id: "knitting", title: "Knitting", icon: "🧵" },
  { id: "sewing", title: "Sewing", icon: "🪡" },
];
